#!/bin/sh
cd "$(git rev-parse --show-toplevel)"

echo "🚀 Running Turbo Checks..."

pnpm lint -- --max-warnings 0
status=$?
if [ $status -ne 0 ]; then
    echo "❌ Linting failed. attempting to fix issues..."
    pnpm lint:fix
    exit $status
fi

pnpm check-types
status=$?
if [ $status -ne 0 ]; then
    echo "❌ Type checking failed. Commit aborted."
    exit $status
fi

echo "✅ checks passed!"
exit 0