services:
  postgres-dgg-political-action:
    container_name: dgg-political-action-postgres-dev
    image: postgres:15-alpine
    ### Because of how payload works, this outputs way too many logs to be of any use.
    ### log_statment options are none (off), ddl, mod, and all (all statements). ddl logs all data definition statements
    command: -c log_statement=none
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dgg-political-action
    ports:
      - '9009:5432' #its over nine thousand!
    volumes:
      - dgg_political_action_postgres_data:/var/lib/postgresql/data

volumes:
  dgg_political_action_postgres_data:
    name: dgg_political_action_postgres_data
