package main

import (
	"encoding/json"
	"os"
	"regexp"
	"text/template"
	"time"

	"fmt"

	"github.com/jmoiron/sqlx"
	_ "github.com/mattn/go-sqlite3"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type volumeRow struct {
  ID           int       `json:"id" db:"id"`
  Title        string    `json:"title" db:"title"`
  VolumeNumber int       `json:"volume_number" db:"volume_number"`
  Description  string    `json:"description" db:"description"`
  EditorsNote  richtextData `json:"editors_note" db:"editors_note"`
  PublishedAt  time.Time `json:"published_at" db:"published_at"`
  Slug         string    `json:"slug" db:"slug"`
  SlugLock     int       `json:"slug_lock" db:"slug_lock"`
  UpdatedAt    time.Time `json:"updated_at" db:"updated_at"`
  CreatedAt    time.Time `json:"created_at" db:"created_at"`
  Status       string    `json:"_status" db:"_status"`
}

type AutoGenerated struct {
	Root struct {
		Children []struct {
			Children []struct {
				Detail  *int    `json:"detail"`
				Format  *int    `json:"format"`
				Mode    *string `json:"mode"`
				Style   *string `json:"style"`
				Text    *string `json:"text"`
				Type    string `json:"type"`
				Version int    `json:"version"`
			} `json:"children,omitempty"`
			Direction  *string `json:"direction,omitempty"`
			Format     *string `json:"format"`
			Indent     *int    `json:"indent,omitempty"`
			Tag        *string `json:"tag,omitempty"`
			TextFormat *int    `json:"textFormat,omitempty"`
			TextStyle  *string `json:"textStyle,omitempty"`
			Fields     *struct {
        ID        string `json:"id"`
				Media     int    `json:"media"`
				BlockName string `json:"blockName"`
				BlockType string `json:"blockType"`
      } `json:"fields,omitempty"`
      Type       string `json:"type"`
      Version    int    `json:"version"`
		} `json:"children"`
		Direction *string `json:"direction"`
		Format    *string `json:"format"`
		Indent    *int    `json:"indent"`
		Type      string  `json:"type"`
		Version   int     `json:"version"`
	} `json:"root"`
}

type richtextData struct {
  Root struct {
    Children []struct {
      Children *[]struct {
        Direction  string `json:"direction" db:"direction"`
        Format     *int   `json:"format" db:"format"`
        Indent     int    `json:"indent" db:"indent"`
        Type       string `json:"type" db:"type"`
        Version    int    `json:"version" db:"version"`
        Tag        string `json:"tag,omitempty" db:"tag,omitempty"`
        TextFormat int    `json:"textFormat,omitempty" db:"textFormat,omitempty"`
        TextStyle  string `json:"textStyle,omitempty" db:"textStyle,omitempty"`
      } `json:"children" db:"children"`
      Direction  string `json:"direction" db:"direction"`
      Format     *int `json:"format" db:"format"`
      Indent     int    `json:"indent" db:"indent"`
      Type       string `json:"type" db:"type"`
      Version    int    `json:"version" db:"version"`
      Tag        string `json:"tag,omitempty" db:"tag,omitempty"`
      TextFormat int    `json:"textFormat,omitempty" db:"textFormat,omitempty"`
      TextStyle  string `json:"textStyle,omitempty" db:"textStyle,omitempty"`
    } `json:"children" db:"children"`
    Direction string `json:"direction" db:"direction"`
    Format    *int `json:"format" db:"format"`
    Indent    int    `json:"indent" db:"indent"`
    Type      string `json:"type" db:"type"`
    Version   int    `json:"version" db:"version"`
  } `json:"root" db:"root"`
}

func main()  {
  log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})

  log.Info().Str("foo", "bar").Msg("Hello world")

  // open read-only database connection
  db, err := sqlx.Connect("sqlite3", "file:../pragmatic-papers.db?cache=shared&mode=ro")
  if err != nil {
    log.Fatal().Err(err).Msg("Failed to open database")
  }

  // Read the volume data from the volume table
  rows, err := db.Queryx("SELECT id, title, volume_number, description, editors_note, published_at, slug, slug_lock, updated_at, created_at, _status FROM volumes")
  if err != nil {
    log.Fatal().Err(err).Msg("Failed to query volume data")
  }

  defer rows.Close()
  var volumes []volumeRow
  for rows.Next() {
    var v volumeRow
    var editorsNoteData string
    var PublishedAt, UpdatedAt, CreatedAt string

    err := rows.Scan(&v.ID, &v.Title, &v.VolumeNumber, &v.Description, &editorsNoteData, &PublishedAt, &v.Slug, &v.SlugLock, &UpdatedAt, &CreatedAt, &v.Status)
    if err != nil {
      log.Fatal().Err(err).Msg("Failed to scan volume row")
    }

    v.PublishedAt, _ = time.Parse(time.RFC3339, PublishedAt)
    v.UpdatedAt, _ = time.Parse(time.RFC3339, UpdatedAt)
    v.CreatedAt, _ = time.Parse(time.RFC3339, CreatedAt)

    // regex replace string with string
    re := regexp.MustCompile(`:\"\"`)
    editorsNoteData = re.ReplaceAllString(editorsNoteData, ":null")

    err = json.Unmarshal([]byte(editorsNoteData), &v.EditorsNote)
    if err != nil {
      log.Fatal().Str("json", editorsNoteData).Err(err).Msg("Failed to unmarshal editors note data")
    }

    log.Info().Interface("volume", v).Msg("Volume data read")

    volumes = append(volumes, v)
  }
  for _, volume := range volumes {
    log.Info().Interface("volume", volume).Msg("Volume data")
  }

  for _, volume := range volumes {
    // output typescript code of the volume data using golang template
    // define a template string
templateString := `// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import { RequiredDataFromCollectionSlug } from 'payload'

export const volume{{.ID}}: () => RequiredDataFromCollectionSlug<'volumes'> = () => {
  return {
    id: {{.ID}},
    title: "{{.Title}}",
    volumeNumber: {{.VolumeNumber}},
    description: "{{.Description}}",
    editorsNote: {
      root: {
        children: [
          {{range .EditorsNote.Root.Children}}
          {
            children: [
              {{if .Children}}
              {{range .Children}}
              {
                {{if .Tag}}tag: "{{.Tag}}",{{end}}
                {{if .TextFormat}}textFormat: {{.TextFormat}},{{end}}
                {{if .TextStyle}}textStyle: "{{.TextStyle}}",{{end}}
                direction: "{{.Direction}}",
                format: {{if .Format}}{{.Format}}{{else}}""{{end}},
                indent: {{.Indent}},
                type: "{{.Type}}",
                version: {{.Version}},
              },
              {{end}}
              {{end}}
            ],
            direction: "{{.Direction}}",
            format: {{if .Format}}{{.Format}}{{else}}""{{end}},
            indent: {{.Indent}},
            type: "{{.Type}}",
            version: {{.Version}},
            {{if .Tag}}tag: "{{.Tag}}",{{end}}
            {{if .TextFormat}}textFormat: {{.TextFormat}},{{end}}
            {{if .TextStyle}}textStyle: "{{.TextStyle}}",{{end}}
          },
          {{end}}
        ],
        direction: "{{.EditorsNote.Root.Direction}}",
        format: {{if .EditorsNote.Root.Format}}{{.EditorsNote.Root.Format}}{{else}}""{{end}},
        indent: {{.EditorsNote.Root.Indent}},
        type: "{{.EditorsNote.Root.Type}}",
        version: {{.EditorsNote.Root.Version}},
      }
    }
  }
}`

    // create a new template
    tmpl, err := template.New("volume").Parse(templateString)
    if err != nil {
      log.Fatal().Err(err).Msg("Failed to parse template")
    }
    // create a file to write the output
    fileName := "../src/endpoints/seed/volumes/volume" + fmt.Sprint(volume.ID) + ".ts"
    file, err := os.Create(fileName)
    if err != nil {
      log.Fatal().Err(err).Msg("Failed to create file")
    }


    err = tmpl.Execute(file, volume)
    if err != nil {
      log.Fatal().Err(err).Msg("Failed to execute template")
    }


    err = file.Close()
    if err != nil {
      log.Fatal().Err(err).Msg("Failed to close file")
    }
  }

  // define a template string for the index file
  indexTemplateString := `import type { Payload } from "payload"
{{range .Volumes}}
import { volume{{.ID}} } from "./volume{{.ID}}"
{{end}}

export const seedVolumes = async ({
  payload,
}: {
  payload: Payload
}): Promise<void> => {
  const volumes = [
    {{range .Volumes}}
    volume{{.ID}},
    {{end}}
  ]

  await Promise.all(
    volumes.map(async (volume) => {
      return payload.create({
        collection: 'volumes',
        data: volume(),
      })
    }),
  )
}`

  // create a new template for the index file
  indexTmpl, err := template.New("index").Parse(indexTemplateString)
  if err != nil {
    log.Fatal().Err(err).Msg("Failed to parse index template")
  }

  // create a file to write the index output
  indexFile, err := os.Create("../src/endpoints/seed/volumes/index.ts")
  if err != nil {
    log.Fatal().Err(err).Msg("Failed to create index file")
  }

  // execute the index template with the volumes data
  err = indexTmpl.Execute(indexFile, map[string]interface{}{
    "Volumes": volumes,
  })
  if err != nil {
    log.Fatal().Err(err).Msg("Failed to execute index template")
  }

  defer db.Close()
}
